Add garce-period flag to gc command
quickwit-inc/quickwit pull request #326
Opened 2021-07-21 13:31 UTC by evanxg852000

### Context / purpose
Closes https://github.com/quickwit-inc/quickwit/issues/320

### Description
- Added `update_timestamp`  member to `SplitMetadata` for tracking when the split was last updated in the metastore
- Added a `grace-period` flag to the `gc` command

### How was this PR tested?
Run the gc command while poking around the metastore file
`./quickwit gc --index-uri file://home/evance/quickwit/data --grace-period 10m`

### Checklist
- [x] tested locally
- [x] added unit tests
- [ ] included documentation

2021-07-22 09:21 UTC, fulmicoton commented on quickwit-cli/src/cli.yaml
> +                help: Threshold period after which intermediate files can be garbage collected.
i did not know the term. I suggest not making that configurable though. 
1h is a good one size fits all parameter.

2021-07-22 09:24 UTC, fulmicoton commented on quickwit-cli/src/main.rs
> +pub fn parse_duration_with_unit(duration: &str) -> anyhow::Result<Duration> {
no need to make the grace period configurable, so we can remove this. Let's keep the snippet and the test though. I am sure it will be useful

2021-07-22 09:26 UTC, fulmicoton requested changes
Can we have unit test to check that GC spares files that are within the grace period?
(and deletes the others)

2021-07-22 12:27 UTC, fulmicoton commented on quickwit-cli/src/main.rs
> +pub fn parse_duration_with_unit(duration: &str) -> anyhow::Result<Duration> {
Marking as resovled as apparently it was requested by Adrien and Frnacois

2021-07-22 12:48 UTC, evanxg852000 commented
@fulmicoton  I have added another test to check that gc does indeed ignore stage splits that are still within the grace period.
We can still remove the `grace-period` flag less code is always better.

2021-07-22 17:15 UTC, guilload commented
Having the grace period not hardcoded allows for testing the gc locally without having to wait for an hour, potentially integration testing, and cleaning up right away when messing up with an index. I'd rather keep it.

2021-07-27 01:57 UTC, fulmicoton approved these changes

2021-07-27 11:45 UTC, merged