Add a health check endpoint on the search server.
quickwit-inc/quickwit pull request #353
Opened 2021-08-04 06:56 UTC by mosuka

### Context / purpose
Add a health check endpoint on the search server. https://github.com/quickwit-inc/quickwit/issues/268

### Description
Port the health check functionality from Barrel.

### How was this PR tested?

```
$ cargo run -- serve --host=0.0.0.0 --index-uri=file:///home/minoru/tmp/quickwit_data/indices/hdfslogs-idx --port=8080
```

```
$ curl 'http://0.0.0.0:8080/health'
```

### Checklist
- [x] tested locally
- [ ] added unit tests
- [ ] included documentation

2021-08-05 14:22 UTC, fmassot commented
Thanks @mosuka for the PR. But I can't merge that for the moment because:
- I think we don't need HTML but only a json response
- We can start by something very simple, like a 200 empty response is good 
- We need to define what health checks we want before

2021-08-05 14:43 UTC, mosuka commented
@fmassot 
I had mistakenly thought that it ported from barrel.
I’ll define the health check specification.
Thanks.

2021-08-06 08:25 UTC, fmassot commented
Can you remove this file?

2021-08-10 04:49 UTC, mosuka commented
@fmassot 
I have simplified the code by removing unnecessary code.
Please take another look.

2021-08-10 12:47 UTC, fmassot requested changes

2021-08-10 12:47 UTC, fmassot commented on quickwit-serve/src/rest.rs
> +        println!("{:?}", resp);
remove the print

2021-08-10 13:03 UTC, mosuka commented on quickwit-serve/src/rest.rs
> +        println!("{:?}", resp);
Removed it. Thanks.

2021-08-10 16:32 UTC, fmassot approved these changes

2021-08-10 16:33 UTC, merged