Remove open_index function from Metastore trait
quickwit-inc/quickwit pull request #54
Opened 2021-05-26 03:15 UTC by mosuka

### Context / purpose
Remove open_index function from Metastore trait.

### Description
https://github.com/quickwit-inc/quickwit/issues/50
Removed `open_index` and `index_exists` from `Metastore` trait.

### How was this PR tested?
Ran `cargo test -- --nocapture test_single_file_metastore`

### Checklist
*Remove or complete this list if required.*
- [x] tested locally
- [x] added unit tests
- [x] included documentation

2021-05-26 06:50 UTC, fulmicoton requested changes
This is no addressing the issue.

When we call list and the index is not loaded, we need to call open_index in a lazy manner.

We need to remove the calls to open_index (and the tests should still pass, as the private method open_index would be called instead of returning an error.)

The `IndexIsNotOpen` error should be removed too.

2021-05-26 11:07 UTC, mosuka commented
I update the PR. Please take another look.

2021-05-26 11:17 UTC, fulmicoton commented on quickwit-metastore/src/metastore/single_file_metastore.rs
> +    cache: Arc<RwLock<HashMap<IndexUri, MetadataSet>>>,
good idea.

2021-05-27 02:35 UTC, fulmicoton approved these changes

2021-05-27 02:35 UTC, merged