add optional tokio-console feature
quickwit-inc/quickwit pull request #825
Opened 2021-12-01 02:08 UTC by PSeitz

### Description
Describe the proposed changes made in this PR.

### How was this PR tested?
Describe how you tested this PR.

2021-12-01 14:45 UTC, fulmicoton commented
Cool! Can you show us tomorrow?

2021-12-01 15:15 UTC, PSeitz commented
yes, but making it work with CI requires some changes

2021-12-21 10:11 UTC, fulmicoton commented on CONTRIBUTING.md
> +1. Clone [tokio-console repository](https://github.com/tokio-rs/console) next to your quickwit repo
```suggestion
1. Install tokio-console by running `cargo install tokio-console`.
```

2021-12-21 10:13 UTC, fulmicoton commented on CONTRIBUTING.md
> +4. Run the console in the tokio-console repo `cargo run`
```suggestion
4. Run `tokio-console`.
```

2021-12-21 10:15 UTC, fulmicoton commented on quickwit-actors/src/async_actor.rs
> +pub(crate) fn spawn_named<T>(
```suggestion
fn spawn_named<T>(
```

2021-12-21 10:15 UTC, fulmicoton commented on quickwit-actors/src/async_actor.rs
> +    let actor_instance_id = ctx.actor_instance_id().to_string();
is the to_string() necessary?

2021-12-21 10:16 UTC, fulmicoton commented on quickwit-actors/src/sync_actor.rs
> +pub(crate) fn spawn_named_blocking<F, R>(f: F, _name: &str) -> tokio::task::JoinHandle<R>
```suggestion
fn spawn_named_blocking<F, R>(f: F, _name: &str) -> tokio::task::JoinHandle<R>
```

2021-12-21 10:17 UTC, fulmicoton commented on quickwit-cli/src/main.rs
> +            return Ok(());
```suggestion
```

2021-12-21 10:18 UTC, fulmicoton requested changes
Not sure if it requires changes or not.

See comments inline

2021-12-21 10:40 UTC, PSeitz commented on quickwit-actors/src/async_actor.rs
> +    let actor_instance_id = ctx.actor_instance_id().to_string();
yes because the context is moved

2021-12-21 10:43 UTC, PSeitz commented on quickwit-cli/src/main.rs
> +            return Ok(());
yes it needs to be disabled

2021-12-21 10:57 UTC, fulmicoton approved these changes

2021-12-21 11:14 UTC, merged