unplug sorting from index config
quickwit-inc/quickwit pull request #934
Opened 2021-12-20 14:30 UTC by PSeitz

fixes #908

### Description
Describe the proposed changes made in this PR.

### How was this PR tested?
Describe how you tested this PR.

2021-12-20 16:21 UTC, fmassot commented on quickwit-metastore/src/metastore/mod.rs
> +            sort_field: None,
I suggest to remove them from the indexing settings

2021-12-20 16:27 UTC, fmassot commented on quickwit-indexing/src/actors/indexer.rs
>      use quickwit_actors::{create_test_mailbox, Universe};
in the indexer actor, we can keep the sort attribute in the indexer state but always set it to None.

2021-12-20 16:28 UTC, fmassot requested changes
See my 2 comments, let's clean a little bit more the sorting stuff :)

2021-12-21 02:33 UTC, fulmicoton commented on quickwit-config/Cargo.toml
> +quickwit-proto = { version = "0.1.0", path = "../quickwit-proto" }
I'm surprised: how do we end up adding dependencies when removing a feature?

2021-12-21 11:45 UTC, closed without merging